#!/usr/bin/env python3
import sqlite3
import sys
conn = sqlite3.connect('social_media.db')
c = conn.cursor()

# Insert some example posts
if sys.argv[1] == 'users':
    conn.execute("INSERT INTO users VALUES (?,?,?)", (sys.argv[2],sys.argv[3],sys.argv[4]))
elif sys.argv[1] == 'followers':
    conn.execute("INSERT INTO followers VALUES (?,?)", (sys.argv[2],sys.argv[3]))
elif sys.argv[1] == 'follows':
    conn.execute("INSERT INTO follows VALUES (?,?)", (sys.argv[2],sys.argv[3]))
elif sys.argv[1] == 'posts':
    conn.execute("INSERT INTO posts VALUES (?,?,?)", (sys.argv[2],sys.argv[3],sys.argv[4]))
elif sys.argv[1] == 'comments':
    conn.execute("INSERT INTO comments VALUES (?,?,?,?,?)", (sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5],sys.argv[6]))
else:
    print('that table in not in the schema')
    # conn.execute("INSERT INTO posts (user_id, content) VALUES (2, 'This is post #2')")
    # conn.execute("INSERT INTO posts (user_id, content) VALUES (1, 'This is post #3')")

# Insert some example comments
# conn.execute("INSERT INTO comments (post_id, user_id, content) VALUES (1, 2, 'This is a comment on post #1')")
# conn.execute("INSERT INTO comments (post_id, user_id, content, parent_id) VALUES (1, 1, 'This is a reply to the first comment', 1)")
# conn.execute("INSERT INTO comments (post_id, user_id, content, parent_id) VALUES (1, 2, 'This is a reply to the reply', 2)")
# conn.execute("INSERT INTO comments (post_id, user_id, content) VALUES (2, 1, 'This is a comment on post #2')")
# conn.execute("INSERT INTO comments (post_id, user_id, content, parent_id) VALUES (1, 2, 'This is a nested reply to the first comment', 3)")
# conn.execute("INSERT INTO comments (post_id, user_id, content) VALUES (1, 1, 'This is another comment on post #1')")
# conn.execute("INSERT INTO comments (post_id, user_id, content, parent_id) VALUES (1, 2, 'This is a reply to the second comment', 6)")

conn.commit()
