#!/bin/bash

python3 insert_data users 1 Harry_Potter BoyWhoLived@gmail.com 
python3 insert_data users 2 Draco_Malfoy youMudBlood@gmail.com
python3 insert_data users 3 Severus_Snape ObviouslySnape@gmail.com
python3 insert_data users 4 Rubeus_Hagrid youreAwizard@gmail.com
python3 insert_data users 5 Albus_Dumbledore PhoenixPower@gmail.com
python3 insert_data users 6 Hermione_Granger schoolRocks@gmail.com
python3 insert_data users 7 Ron_Weasley itsLeviosA@gmail.com
python3 insert_data users 8 Sirius_Black wolfUncle@gmail.com
python3 insert_data users 9 Bellatrix_Lestrange iKilledSirius@gmail.com
python3 insert_data users 10 Neville_Longbottom BadWithBrooms@gmail.com
python3 insert_data users 11 Remus_Lupin DrWerewolf@gmail.com
python3 insert_data users 12 Dobby FreedBySock@gmail.com
python3 insert_data users 13 Lord_Voldemort AvadaKedavra@gmail.com
python3 insert_data users 14 Alastor_Moody CrazyEye@gmail.com
python3 insert_data users 15 Minerva_Mcgonagall Fiftypoints@gmail.com
python3 insert_data users 16 Dolores_Umbridge ChildPunisher@gmail.com
python3 insert_data users 17 Luna_Lovegood brightFuture@gmail.com
python3 insert_data users 18 Cedric_Diggory twilightboy@gmail.com
python3 insert_data users 19 Newt_Scamander fantasticBeasts@gmail.com
python3 insert_data users 20 Gilderoy_Lockhart charmingConArtist@gmail.com
python3 insert_data users 21 Cho_Chang HarrysFirstCrush@gmail.com
python3 insert_data users 22 Pomona_Sprout herbology@gmail.com
python3 insert_data users 23 Hannah_Abbott iKnowHarry@gmail.com
python3 insert_data users 24 Myrtle_Warren moaningMyrtle@gmail.com
python3 insert_data users 25 Marcus_Belby quidditchSeeker@gmail.com
python3 insert_data users 26 Garrick_Ollivander wandmaker@gmail.com
python3 insert_data users 27 Quirinus_Quirrell likesDarkArts@gmail.com


python3 insert_data follows 1 8 
python3 insert_data follows 1 12
python3 insert_data follows 1 15
python3 insert_data follows 1 4
python3 insert_data follows 1 3
python3 insert_data follows 2 11
python3 insert_data follows 2 13
python3 insert_data follows 2 15
python3 insert_data follows 3 2
python3 insert_data follows 3 4
python3 insert_data follows 4 1
python3 insert_data follows 4 11
python3 insert_data follows 4 15
python3 insert_data follows 4 3
python3 insert_data follows 5 6
python3 insert_data follows 5 15
python3 insert_data follows 6 4
python3 insert_data follows 6 1
python3 insert_data follows 6 3
python3 insert_data follows 7 6
python3 insert_data follows 7 5
python3 insert_data follows 8 13
python3 insert_data follows 8 16
python3 insert_data follows 8 15
python3 insert_data follows 8 9
python3 insert_data follows 8 6
python3 insert_data follows 8 4
python3 insert_data follows 9 11
python3 insert_data follows 9 15
python3 insert_data follows 9 16
python3 insert_data follows 9 1
python3 insert_data follows 9 4
python3 insert_data follows 9 6
python3 insert_data follows 9 10
python3 insert_data follows 10 1
python3 insert_data follows 10 4
python3 insert_data follows 10 16
python3 insert_data follows 10 14
python3 insert_data follows 10 13
python3 insert_data follows 10 15
python3 insert_data follows 11 15
python3 insert_data follows 11 1
python3 insert_data follows 11 4
python3 insert_data follows 11 6 
python3 insert_data follows 11 16
python3 insert_data follows 12 16
python3 insert_data follows 12 7
python3 insert_data follows 12 1
python3 insert_data follows 12 6
python3 insert_data follows 12 5
python3 insert_data follows 12 13
python3 insert_data follows 13 12
python3 insert_data follows 13 8
python3 insert_data follows 13 2
python3 insert_data follows 13 7
python3 insert_data follows 13 4
python3 insert_data follows 13 6
python3 insert_data follows 13 3
python3 insert_data follows 13 5
python3 insert_data follows 14 15
python3 insert_data follows 14 8
python3 insert_data follows 14 4
python3 insert_data follows 14 16
python3 insert_data follows 14 1
python3 insert_data follows 14 2
python3 insert_data follows 14 5
python3 insert_data follows 14 6
python3 insert_data follows 15 14
python3 insert_data follows 15 6
python3 insert_data follows 15 4
python3 insert_data follows 15 1
python3 insert_data follows 15 11
python3 insert_data follows 15 7
python3 insert_data follows 15 9
python3 insert_data follows 16 1
python3 insert_data follows 16 15
python3 insert_data follows 16 3
python3 insert_data follows 16 6
python3 insert_data follows 16 9
python3 insert_data follows 16 10
python3 insert_data follows 16 11
python3 insert_data follows 16 8
python3 insert_data follows 16 4
python3 insert_data follows 16 2
python3 insert_data follows 17 7
python3 insert_data follows 18 1
python3 insert_data follows 19 3
python3 insert_data follows 20 7
python3 insert_data follows 21 5
python3 insert_data follows 22 2
python3 insert_data follows 23 6
python3 insert_data follows 24 9
python3 insert_data follows 25 11
python3 insert_data follows 26 4
python3 insert_data follows 27 8

python3 insert_data house 1 Gryffindor
python3 insert_data house 2 Slytherin
python3 insert_data house 3 Slytherin
python3 insert_data house 4 Gryffindor
python3 insert_data house 5 Gryffindor
python3 insert_data house 6 Gryffindor
python3 insert_data house 7 Gryffindor
python3 insert_data house 8 Gryffindor
python3 insert_data house 9 Slytherin
python3 insert_data house 10 HufflePuff
python3 insert_data house 11 Gryffindor
python3 insert_data house 12 Slytherin
python3 insert_data house 13 Slytherin
python3 insert_data house 14 HufflePuff
python3 insert_data house 15 Gryffindor
python3 insert_data house 16 Slytherin
python3 insert_data house 17 Ravenclaw
python3 insert_data house 18 HufflePuff
python3 insert_data house 19 HufflePuff
python3 insert_data house 20 Ravenclaw
python3 insert_data house 21 Ravenclaw
python3 insert_data house 22 HufflePuff
python3 insert_data house 23 HufflePuff
python3 insert_data house 24 Ravenclaw
python3 insert_data house 25 Ravenclaw
python3 insert_data house 26 Ravenclaw
python3 insert_data house 27 Ravenclaw

python3 insert_data posts
python3 insert_data comments
